cernerFhirServerUrl = "https://fhir-ehr-code.cerner.com/r4/ec2458f2-1e24-41c8-b71b-0e701af7583d"
cernerTokenUrl = "https://authorization.cerner.com/tenants/ec2458f2-1e24-41c8-b71b-0e701af7583d/protocols/oauth2/profiles/smart-v1/token"
cernerClientId = "977f278f-eb3f-411e-b2ff-16c554501d69"
cernerClientSecret = "AW0nwz9LqNrb_pTzxUHsbqey1f0bzRv_"
scopes = ["system/Patient.read", "system/Patient.write"]

[ballerina.http.accessLogConfig]
# Enable printing access logs on the Console. The default value is `false`.
console = true

[ballerina.http.traceLogAdvancedConfig]
# Enable printing trace logs on the Console. The default value is `false`.
console = true